env:
  global:
  - secure: fS4SKKQueUog7+QUMYc4XmERfVUHRQYgDw4YsCC0hYKPzTpfoGwfZgUfg9DIQp8QbmY5bHCbABvN/gsD1pvKG19dfUTxSYTmwLHx9mm2zFOlM0lyxhNRgwZ8B4Y0Fu8N9rQqO/fjFAV35/jnH8YrEWgJ6aKYNr2feMRzGQL69e3Txq3r2WRiqzL0FUCw5gDUOjLoqyvy3/YJvDm0rNenmx0jV8RME0GOS8jT6TdbsCv6dcYtOR9TSFqe9O8wjhIkhY4wEwJnSo8UmMB7hJgyLDrQUDcGP9XQal/8kuGAY+KDyTPYcIOHszusPhBv7N48X8MR2ef9pa5W65f6fYUIjgTThnFiKWOIlZP+YdPhPHJzPAOgmCqHWx24zQYrNgFsZGu1ChZffzN9v99h5vV0ramDRqKbWCiovUNK6ol6Dc8SGIBiTZgvhFUiyFtD1Bk3r+ll+NhkrYtsG19cQ6ikdyJbQOMCerNBshx69/LrbAXQPOKxibqPqmNP+3h83vzv/WA879UpgECgS+zB4lZbmtirAhCbxN8lSQjUoSJj2dah0FbYHV8i1Qmt22NyMXDAAREHmMq6CYmq89095B+G8tDammD+4JGBhRjwLAhRPiF5hNiABzTgAcLsLVs+lg9rbZNl/Drm4gxeumyt2zho3EaBrIaBPnuwKL+BquLYg80=

  matrix:
  include:
  - name: Android Build
    language: android
    jdk: openjdk8
    android:
      components:
      - build-tools-28.0.3
      - android-28
    before_install:
    - yes | sdkmanager --update
    before_script:
    - openssl aes-256-cbc -k "$travis_password" -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - git clone https://github.com/flutter/flutter.git -b beta
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - gem install bundler && cd android && bundle install && cd ..
    script:
    - flutter packages get
    - flutter test
    - flutter build apk
