matrix:
  include:
  - name: Android Build
    language: android
    jdk: openjdk8
    android:
      components:
      - build-tools-28.0.3
      - android-28
    before_script:
    - tar xvf secrets.tar
    - git clone https://github.com/flutter/flutter.git -b beta
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - gem install bundler && cd android && bundle install && cd ..
    script:
    - flutter packages get
    - flutter test
    - flutter build apk
    - cd android && bundle exec fastlane internal

env:
  global:
  - secure: RPzBGTerjX01mpkn9eoTkkueFFjm3XLuBhQngR9Dr6ld8cBsQvg1Gt7JDawY4lQXV9p4xT6po4x4cITaBcuWkSekNQSuOA/PaEOR9YE/2Z29zbQgP/BG5vjYTA7qXioOlwKBtJYRMZK2AgUePony/iXiY6+sJSp6D4l6lQx69d7q6930ubQkjZD4xuXf/Kb2k0Pi4iVZdPNXn1HkG34f+XuNcVji6O/q5KXleBV6NsCcb7Gv3w4jcdepbRWVRvPJSNKt7b82M4GTt7Yj/9pn//EFX6jBcBTFurfiZb7dd+RSaW4Erb4GWM7skALbrhJ9iKy7yeBF2OVLGyFZYgxGo6DLHhJjmqVR+J+8+CCcakmuHo/DmYBJa/nITltpfho3iSvqPNFyN7jSfBpESbvDNAEfrQpkYRmTHQBlKycTsSPhOBPIDAFe7kqlB5k2t4LDFjd8axhfiLuSwKZ2+I407UIOBbxqmtnh+Ug7o2IRx12X0qbH7JK147vEnn8L5JFwEl/vFkJ5X0Oo+oklELHF9XYMbGvjDQIkqd/9nZj5bIc9qn8Uw2A0Mg0f+yovb3DtIKpVoNXOBUHRKd8GihnS1FXhnFPWsIGrC4huM0igv1Xg02pmiDd5w2VIO/A1b6HRt6CCT0Tn+Q7vspSN/Uk3aK9evWLr0kxMIx0MEXMUUiQ=
before_install:
  - openssl aes-256-cbc -k "encription_password" -in secrets.tar.enc -out secrets.tar -d