name: daf_plus_plus
description: A daf a day...
version: 0.3.0+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.4
  firebase_crashlytics: ^0.1.3
  cloud_firestore: ^0.13.4
  mobx: ^1.0.0
  intl: ^0.16.1
  flutter_mobx: ^1.0.0
  fluttertoast: ^3.1.3
  google_fonts: ^0.3.9
  flutter_widgets: ^0.1.11
  flutter_sticky_header: 0.4.1
  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^1.2.2
  url_launcher: ^5.4.2
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/he.json
    - assets/icon/daf-white-on-transperant.png
    - assets/icon/pp-white-on-transperant.png