name: daf_counter
description: A new Flutter project.
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3

  fluttertoast: ^3.1.3
  google_fonts: ^0.3.9
  flutter_widgets: ^0.1.11
  flutter_sticky_header: 0.4.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
