name: daf_plus_plus
description: A daf a day...
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^1.4.0+1
  hive_flutter: ^0.3.0+1
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.4

  fluttertoast: ^3.1.3
  google_fonts: ^0.3.9
  flutter_widgets: ^0.1.11
  flutter_sticky_header: 0.4.1
  cupertino_icons: ^0.1.2
  firebase_crashlytics: ^0.1.3
  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/he.json
    - assets/avoda-zara.json
    - assets/bava-basra.json
    - assets/bava-kama.json
    - assets/bava-metziah.json
    - assets/bechoros.json
    - assets/beitzah.json
    - assets/brachos.json
    - assets/chagigah.json
    - assets/chullin.json
    - assets/erechin.json
    - assets/eruvin.json
    - assets/gittin.json
    - assets/horiyos.json
    - assets/kedushin.json
    - assets/kesuvos.json
    - assets/krisos.json
    - assets/makkos.json
    - assets/megillah.json
    - assets/meilah.json
    - assets/menuchos.json
    - assets/moed-katan.json
    - assets/nazir.json
    - assets/nedarim.json
    - assets/niddah.json
    - assets/pesachim.json
    - assets/rosh-hashanah.json
    - assets/sanhedrin.json
    - assets/shabbos.json
    - assets/shavuos.json
    - assets/shekalim.json
    - assets/sota.json
    - assets/sukkah.json
    - assets/taanis.json
    - assets/temora.json
    - assets/yevamos.json
    - assets/yoma.json
    - assets/zevachim.json
