default_platform(:android)

platform :android do |lane, options|
  desc "Deploy a new beta"
  lane :beta do
      firebase_app_distribution(
          app: options[:APP_ID],
          groups: "testers",
          token: options[:FIREBASE_TOKEN],
          release_notes: "a new version",
          firebase_cli_path: "C:/Users/zvi/AppData/Roaming/npm/firebase",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
end
